// src/components/Footer.jsx
import { ArrowUpRight, Github, Globe2, Linkedin, Mail } from 'lucide-react'
import { useRef } from 'react'
import { useGSAP, useReducedMotionSafe, gsap } from '../lib/gsap'

export default function Footer({ data = {} }) {
  const reduceMotion = useReducedMotionSafe()
  const ref = useRef(null)
  const linkedin = data.socialLinks?.find((item) => item.name === 'LinkedIn')

  useGSAP(() => {
    if (reduceMotion) return
    gsap.fromTo('.footer-heading', { opacity: 0, y: 32 }, { opacity: 1, y: 0, duration: 0.75, ease: 'expo.out',
      scrollTrigger: { trigger: ref.current, start: 'top 85%', once: true } })
    gsap.fromTo('.footer-desc', { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.6, ease: 'expo.out', delay: 0.12,
      scrollTrigger: { trigger: ref.current, start: 'top 85%', once: true } })
    gsap.fromTo('.social-link', { opacity: 0, y: 12 },
      { opacity: 1, y: 0, duration: 0.4, ease: 'power2.out', stagger: 0.07,
        scrollTrigger: { trigger: ref.current, start: 'top 88%', once: true } })
  }, { scope: ref, revertOnUpdate: true })

  return (
    <footer id="contact" ref={ref} className="container-shell py-20 sm:py-28">
      <div className="footer-heading grid gap-10 border-b border-line pb-14 lg:grid-cols-[1fr_auto] lg:items-end">
        <div>
          <p className="text-xs font-bold text-coral">{data.eyebrow}</p>
          <h2 className="mt-5 max-w-2xl text-[clamp(2.9rem,6vw,6rem)] font-bold leading-[0.92] tracking-[-0.08em]">{data.title}</h2>
          <p className="footer-desc mt-5 max-w-xl text-base leading-7 text-muted">{data.description}</p>
        </div>
        <div className="flex flex-col items-start gap-4 lg:items-end">
          <a
            href={`mailto:${data.email ?? 'darelrafif.kz@gmail.com'}`}
            className="inline-flex items-center gap-2 rounded-full bg-coral px-5 py-3 text-sm font-bold text-canvas transition hover:-translate-y-0.5 hover:bg-ink active:translate-y-0"
          >
            Let&apos;s work together <ArrowUpRight size={16} strokeWidth={1.8} />
          </a>
          {linkedin?.url && linkedin.url !== '#' && (
            <a href={linkedin.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-ink transition hover:text-coral">
              LinkedIn profile
            </a>
          )}
        </div>
      </div>

      <div className="flex flex-col justify-between gap-8 pt-8 sm:flex-row sm:items-center">
        <div>
          <a href="#home" className="text-lg font-bold tracking-[-0.08em]">darelrk<span className="text-coral">.</span></a>
          <p className="mt-2 text-xs text-muted">{data.copyright}</p>
        </div>
        <nav className="flex flex-wrap items-center gap-4" aria-label="Social links">
          {data.socialLinks?.map((social) => {
            const Icon = { GitHub: Github, LinkedIn: Linkedin, Medium: Globe2, Kaggle: Globe2 }[social.name] ?? Mail
            const disabled = social.url === '#'
            return (
              <a
                key={social.name}
                href={disabled ? undefined : social.url}
                target={disabled ? undefined : '_blank'}
                rel={disabled ? undefined : 'noreferrer'}
                aria-disabled={disabled}
                className={`social-link inline-flex items-center gap-2 text-sm transition ${disabled ? 'cursor-not-allowed text-muted/50' : 'text-ink hover:text-coral'}`}
              >
                <Icon size={16} strokeWidth={1.7} />
                {social.name}
              </a>
            )
          })}
        </nav>
      </div>
    </footer>
  )
}

// src/components/layout/Footer.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { profile } from '../../data/portfolio'
import { Github, Linkedin, Mail, ArrowUp, BookOpen } from 'lucide-vue-next'

const footerRef = ref<HTMLElement | null>(null)
const isVisible = ref(false)
const dividerActive = ref(false)
const sweepActive = ref(false)

function scrollTop() {
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

onMounted(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          isVisible.value = true
          dividerActive.value = true
          // Delay sweep so heading animates in first
          setTimeout(() => {
            sweepActive.value = true
          }, 600)
          observer.disconnect()
        }
      })
    },
    { threshold: 0.15 }
  )

  if (footerRef.value) {
    observer.observe(footerRef.value)
  }
})

const socialLinks = [
  { href: `mailto:${profile.email}`, icon: Mail, label: 'Email' },
  { href: profile.links.linkedin, icon: Linkedin, label: 'LinkedIn', external: true },
  { href: profile.links.github, icon: Github, label: 'GitHub', external: true },
  { href: profile.links.medium, icon: BookOpen, label: 'Medium', external: true },
]
</script>

<template>
  <footer
    id="contact"
    ref="footerRef"
    class="px-6 py-20 footer-divider"
    :class="{ 'animate-divider': dividerActive }"
  >
    <!-- CTA -->
    <div
      class="max-w-2xl mx-auto text-center mb-12 transition-all duration-700 ease-out"
      :style="{
        opacity: isVisible ? 1 : 0,
        transform: isVisible ? 'translateY(0)' : 'translateY(30px)',
      }"
    >
      <h2
        class="text-4xl md:text-5xl font-bold mb-4"
        :class="{ 'gradient-sweep-text': true, 'animate-sweep': sweepActive }"
      >
        Let's Connect<span style="color: var(--accent); -webkit-text-fill-color: var(--accent)">.</span>
      </h2>
      <p
        class="text-base transition-all duration-700 delay-200 ease-out"
        :style="{
          opacity: isVisible ? 1 : 0,
          transform: isVisible ? 'translateY(0)' : 'translateY(15px)',
          color: 'var(--text-secondary)',
        }"
      >
        Open for collaboration in data science, analysis, and machine learning projects.
      </p>
    </div>

    <!-- Links (Staggered) -->
    <div class="flex flex-wrap justify-center gap-4 mb-12">
      <a
        v-for="(link, index) in socialLinks"
        :key="link.label"
        :href="link.href"
        :target="link.external ? '_blank' : undefined"
        :rel="link.external ? 'noopener noreferrer' : undefined"
        class="glass-btn transition-all duration-500 ease-out"
        :style="{
          opacity: isVisible ? 1 : 0,
          transform: isVisible ? 'translateY(0)' : 'translateY(20px)',
          transitionDelay: `${400 + index * 100}ms`,
        }"
      >
        <component :is="link.icon" :size="18" />
        {{ link.label }}
      </a>
    </div>

    <!-- Bottom -->
    <div
      class="flex items-center justify-between max-w-4xl mx-auto pt-8 transition-all duration-700 ease-out"
      :style="{
        opacity: isVisible ? 1 : 0,
        borderTop: '1px solid var(--border)',
        transitionDelay: '800ms',
      }"
    >
      <p class="text-xs" style="color: var(--text-secondary)">
        © {{ new Date().getFullYear() }} {{ profile.name }}
      </p>
      <button
        class="w-10 h-10 flex items-center justify-center rounded-full transition-all hover:bg-[rgba(220,38,38,0.15)]"
        :class="{ 'btn-pulse': isVisible }"
        style="border: 1px solid var(--border-hover); color: var(--text-secondary)"
        @click="scrollTop"
        aria-label="Back to top"
      >
        <ArrowUp :size="16" />
      </button>
    </div>
  </footer>
</template>
